// glimglab_react/src/App.js
import './App.css';
import { logo } from './assets/images/logo192.png';

function App() {
  return (
    <div className="container">
      <header className="main-header">
        <section className="logo">
          <a href="#">imglab</a>
        </section>
        <div className="main-action">
          <ul>
            <li className="main-action__item">
              <a id="load-image-btn" href="#">
                upload<input type="file" style={{display: 'none'}} id="fileInput" />
              </a>
            </li>
            <li className="main-action__item"><a id="download-btn" href="#">download</a></li>
          </ul>
        </div>
      </header>

      <section class="middle-area">
        {/* <app-sidemenu></app-sidemenu>
        <app-workarea></app-workarea> */}
        {/* <gl-img filters='[]' src="./assets/images/logo192.png"></gl-img> */}
        <img filters='[]' src={{logo}}></img>
      </section>

      <footer>
        <p>&copy; 2020 Developed by Wei Zhou. All rights reserved.</p>
      </footer>
    </div>
  );
}

export default App;

// glimglab_ang/src/app/app.component.ts
import { Component } from '@angular/core';
import { ImageService } from './image.service';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  title = 'glimglab';
  selectedFile?: File;

  constructor(private imageService: ImageService) {
  }

  loadImage(event: any): void {
    this.selectedFile = event.target.files[0];
    // tslint:disable-next-line: no-unused-expression
    this.selectedFile && this.imageService.addLabImage(this.selectedFile);
  }
}


<header class="main-header">
  <section class="logo">
    <a href="#">imglab</a>
  </section>
  <div class="main-action">
    <ul>
      <li class="main-action__item">
        <a id="load-image-btn" (click)="fileInput.click()" href="#">
          upload<input type="file" style="display: none" (change)="loadImage($event)" #fileInput>
        </a>
      </li>
      <li class="main-action__item"><a id="download-btn" href="#">download</a></li>
    </ul>
  </div>
</header>

<section class="middle-area">
  <app-sidemenu></app-sidemenu>
  <app-workarea></app-workarea>
</section>

<footer>
  <p>&copy; 2020 Developed by Wei Zhou. All rights reserved.</p>
</footer>
